### PR TITLE
remove comments and console.logs

### PR DESCRIPTION
**Pull request by rickbacci**
#### What's this PR do?

refactor code to remove comments and console.logs
#### Where should the reviewer start?

Changes made to one file only.
#### How should this be manually tested?

You can update the idea body in one of the ideas to verify that the code still works.

What gif best describes this PR or how it makes you feel?

Feels good to refactor ;)

@egogre @rrgayhart

### CODE REVIEW

**Comment by RichardLitt** [comment]
lgtm

**Comment by rickbacci** [comment]
Thanks Richard. We are refactoring today, so I figure I will try to implement some of the things you recommended.

**Comment by RichardLitt** [comment]
Refactoring = the best kind of *ing

**Comment by rrgayhart** [comment]
Noice! 

Be careful with including updates to the Gem versions in unrelated PRs though. Totally not a big deal here, but if this were a group project it could cause issues for other people working in the project if they have trouble updating the gems.

:ship: it!

**Comment by George-Hudson** [comment]
Pretty straightforward. Nice work.
:computer: :spaghetti: it!

**Pull request merged**
